In [1]:
import torch
#gpu 사용 가능 여부
print(torch.cuda.is_available())
# True
#gpu 장치의 인덱스
print(torch.cuda.current_device())
# 0
# 사용가능한 gpu 장치수
print(torch.cuda.device_count())
# 1
# gpu의 이름
print(torch.cuda.get_device_name(0))

True
0
1
NVIDIA GeForce GTX 1050 Ti


In [2]:
import torch
# Default CUDA device
cuda = torch.device('cuda')
# 텐서 자료를 gpu에 저장
a = torch.tensor([1, 2], device=cuda)
b = torch.tensor([1, 2]).cuda()
c = torch.tensor([1, 2]).to(device=cuda)
print(a)
print(b)
print(c)

tensor([1, 2], device='cuda:0')
tensor([1, 2], device='cuda:0')
tensor([1, 2], device='cuda:0')


In [3]:
#사용하지 않는 텐서 정리
torch.cuda.empty_cache()