In [1]:
import tensorflow as tf
import sys
print(sys.version)
print(tf.__version__)

3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
2.10.0


In [2]:
# 상수 선언
hello = tf.constant('Hello World')
print(hello)
print(hello.numpy()) #바이트 배열
print(hello.numpy().decode('utf-8')) # 바이트 배열을 스트링으로 변환
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
#c = a+b
print(c.numpy())
print([a.numpy(),b.numpy(),c.numpy()])

tf.Tensor(b'Hello World', shape=(), dtype=string)
b'Hello World'
Hello World
42
[10, 32, 42]


In [3]:
node1=tf.constant(3.0)
node2=tf.constant(4.0)
node3=tf.add(node1,node2)
print(node3.numpy())

7.0


In [4]:
def output(a,b):
    return tf.multiply(a, b)

print(output(3.0, 5.0).numpy())
print(output(0.0, 6.0).numpy())
print(output([2.0,3.1,7.4], [6.0,2.5,3.1]).numpy())

15.0
0.0
[12.    7.75 22.94]


In [5]:
#텐서플로의 변수 선언
W = tf.Variable([0.3], dtype=tf.float32)
b = tf.Variable([-0.3], dtype=tf.float32)

def linear_model(x):
    return tf.multiply(W,tf.add(x,b))

x=[1.,2.,3.,4.]
# x의 값에 따라 linear_model 계산
linear_model(x).numpy()

array([0.21000001, 0.51000005, 0.81000006, 1.11      ], dtype=float32)

In [7]:
import numpy as np
X = np.array([[1,2,3],[4,5,6]])
print('X\n',X)

#3행 2열의 랜덤
W = np.array([[np.random.randint(10) for col in range(2)] for row in range(3)])
print('W\n',W)

b = np.array([[np.random.randint(10) for col in range(1)] for row in range(2)])
print('b\n',b)

X
 [[1 2 3]
 [4 5 6]]
W
 [[8 1]
 [4 0]
 [8 9]]
b
 [[2]
 [2]]


In [8]:
def expr(X):
    return tf.matmul(X, W) +b #행렬 곱셈

expr(X).numpy()

array([[ 42,  30],
       [102,  60]])